Answer.create!([
  {user_id: 1, question_id: 1, option_id: 1},
  {user_id: 1, question_id: 12, option_id: 30},
  {user_id: 1, question_id: 16, option_id: 38},
  {user_id: 1, question_id: 13, option_id: 32},
  {user_id: 1, question_id: 10, option_id: 26},
  {user_id: 1, question_id: 11, option_id: 27},
  {user_id: 1, question_id: 14, option_id: 33},
  {user_id: 1, question_id: 2, option_id: 4},
  {user_id: 1, question_id: 9, option_id: 23},
  {user_id: 1, question_id: 17, option_id: 40},
  {user_id: 1, question_id: 3, option_id: 7},
  {user_id: 1, question_id: 6, option_id: 16},
  {user_id: 1, question_id: 7, option_id: 17},
  {user_id: 1, question_id: 4, option_id: 9},
  {user_id: 1, question_id: 15, option_id: 36},
  {user_id: 1, question_id: 5, option_id: 12},
  {user_id: 1, question_id: 8, option_id: 22},
  {user_id: 2, question_id: 2, option_id: 5},
  {user_id: 3, question_id: 14, option_id: 33},
  {user_id: 3, question_id: 10, option_id: 26},
  {user_id: 3, question_id: 5, option_id: 12},
  {user_id: 3, question_id: 2, option_id: 4},
  {user_id: 3, question_id: 15, option_id: 36},
  {user_id: 3, question_id: 17, option_id: 40},
  {user_id: 3, question_id: 3, option_id: 7},
  {user_id: 3, question_id: 9, option_id: 23},
  {user_id: 3, question_id: 4, option_id: 9},
  {user_id: 3, question_id: 16, option_id: 38},
  {user_id: 3, question_id: 8, option_id: 22},
  {user_id: 3, question_id: 11, option_id: 27},
  {user_id: 3, question_id: 1, option_id: 1},
  {user_id: 3, question_id: 13, option_id: 32},
  {user_id: 3, question_id: 12, option_id: 30},
  {user_id: 3, question_id: 7, option_id: 17},
  {user_id: 3, question_id: 6, option_id: 16},
  {user_id: 4, question_id: 15, option_id: 35},
  {user_id: 4, question_id: 1, option_id: 1},
  {user_id: 4, question_id: 14, option_id: 34},
  {user_id: 4, question_id: 13, option_id: 31},
  {user_id: 4, question_id: 3, option_id: 7},
  {user_id: 4, question_id: 5, option_id: 10},
  {user_id: 4, question_id: 11, option_id: 28},
  {user_id: 4, question_id: 6, option_id: 16},
  {user_id: 4, question_id: 12, option_id: 30},
  {user_id: 4, question_id: 8, option_id: 22},
  {user_id: 4, question_id: 4, option_id: 8},
  {user_id: 4, question_id: 7, option_id: 20},
  {user_id: 4, question_id: 17, option_id: 41},
  {user_id: 4, question_id: 9, option_id: 24},
  {user_id: 4, question_id: 16, option_id: 37},
  {user_id: 4, question_id: 2, option_id: 4},
  {user_id: 4, question_id: 10, option_id: 26},
  {user_id: 5, question_id: 11, option_id: 27},
  {user_id: 5, question_id: 10, option_id: 26},
  {user_id: 5, question_id: 12, option_id: 30},
  {user_id: 5, question_id: 14, option_id: 33},
  {user_id: 5, question_id: 17, option_id: 41},
  {user_id: 5, question_id: 2, option_id: 5},
  {user_id: 5, question_id: 8, option_id: 22},
  {user_id: 5, question_id: 13, option_id: 32},
  {user_id: 5, question_id: 16, option_id: 38},
  {user_id: 5, question_id: 5, option_id: 12},
  {user_id: 5, question_id: 1, option_id: 1},
  {user_id: 5, question_id: 3, option_id: 7},
  {user_id: 5, question_id: 6, option_id: 16},
  {user_id: 5, question_id: 7, option_id: 17},
  {user_id: 5, question_id: 4, option_id: 9},
  {user_id: 5, question_id: 9, option_id: 23},
  {user_id: 5, question_id: 15, option_id: 36},
  {user_id: 6, question_id: 15, option_id: 36},
  {user_id: 6, question_id: 17, option_id: 40},
  {user_id: 6, question_id: 12, option_id: 30},
  {user_id: 6, question_id: 5, option_id: 10},
  {user_id: 6, question_id: 7, option_id: 17},
  {user_id: 6, question_id: 6, option_id: 16},
  {user_id: 6, question_id: 14, option_id: 34},
  {user_id: 6, question_id: 3, option_id: 6},
  {user_id: 6, question_id: 16, option_id: 37},
  {user_id: 6, question_id: 11, option_id: 28},
  {user_id: 6, question_id: 10, option_id: 25},
  {user_id: 6, question_id: 8, option_id: 21},
  {user_id: 6, question_id: 1, option_id: 1},
  {user_id: 6, question_id: 2, option_id: 4},
  {user_id: 6, question_id: 9, option_id: 23},
  {user_id: 6, question_id: 13, option_id: 32},
  {user_id: 6, question_id: 4, option_id: 9},
  {user_id: 7, question_id: 1, option_id: 1},
  {user_id: 7, question_id: 2, option_id: 4},
  {user_id: 7, question_id: 3, option_id: 7},
  {user_id: 7, question_id: 4, option_id: 8},
  {user_id: 7, question_id: 5, option_id: 10},
  {user_id: 7, question_id: 6, option_id: 15},
  {user_id: 7, question_id: 7, option_id: 17},
  {user_id: 7, question_id: 8, option_id: 21},
  {user_id: 7, question_id: 9, option_id: 24},
  {user_id: 7, question_id: 10, option_id: 25},
  {user_id: 7, question_id: 11, option_id: 28},
  {user_id: 7, question_id: 12, option_id: 30},
  {user_id: 7, question_id: 13, option_id: 31},
  {user_id: 7, question_id: 14, option_id: 34},
  {user_id: 7, question_id: 15, option_id: 35},
  {user_id: 7, question_id: 16, option_id: 39},
  {user_id: 7, question_id: 17, option_id: 41},
  {user_id: 8, question_id: 1, option_id: 3},
  {user_id: 8, question_id: 2, option_id: 5},
  {user_id: 8, question_id: 3, option_id: 6},
  {user_id: 8, question_id: 4, option_id: 8},
  {user_id: 8, question_id: 5, option_id: 13},
  {user_id: 8, question_id: 6, option_id: 16},
  {user_id: 8, question_id: 7, option_id: 20},
  {user_id: 8, question_id: 8, option_id: 21},
  {user_id: 8, question_id: 9, option_id: 23},
  {user_id: 8, question_id: 10, option_id: 25},
  {user_id: 8, question_id: 11, option_id: 28},
  {user_id: 8, question_id: 12, option_id: 29},
  {user_id: 8, question_id: 13, option_id: 32},
  {user_id: 8, question_id: 14, option_id: 34},
  {user_id: 8, question_id: 15, option_id: 35},
  {user_id: 8, question_id: 16, option_id: 38},
  {user_id: 8, question_id: 17, option_id: 41},
  {user_id: 10, question_id: 1, option_id: 3},
  {user_id: 10, question_id: 2, option_id: 4},
  {user_id: 10, question_id: 3, option_id: 7},
  {user_id: 10, question_id: 4, option_id: 9},
  {user_id: 10, question_id: 5, option_id: 10},
  {user_id: 10, question_id: 6, option_id: 15},
  {user_id: 10, question_id: 7, option_id: 19},
  {user_id: 10, question_id: 8, option_id: 22},
  {user_id: 10, question_id: 9, option_id: 23},
  {user_id: 10, question_id: 10, option_id: 25},
  {user_id: 10, question_id: 11, option_id: 27},
  {user_id: 10, question_id: 12, option_id: 30},
  {user_id: 10, question_id: 13, option_id: 31},
  {user_id: 10, question_id: 14, option_id: 33},
  {user_id: 10, question_id: 15, option_id: 36},
  {user_id: 10, question_id: 16, option_id: 39},
  {user_id: 10, question_id: 17, option_id: 41},
  {user_id: 11, question_id: 1, option_id: 3},
  {user_id: 11, question_id: 2, option_id: 5},
  {user_id: 11, question_id: 3, option_id: 6},
  {user_id: 11, question_id: 4, option_id: 9},
  {user_id: 11, question_id: 5, option_id: 13},
  {user_id: 11, question_id: 6, option_id: 15},
  {user_id: 11, question_id: 7, option_id: 20},
  {user_id: 11, question_id: 8, option_id: 21},
  {user_id: 11, question_id: 9, option_id: 23},
  {user_id: 11, question_id: 10, option_id: 26},
  {user_id: 11, question_id: 11, option_id: 27},
  {user_id: 11, question_id: 12, option_id: 30},
  {user_id: 11, question_id: 13, option_id: 31},
  {user_id: 11, question_id: 14, option_id: 34},
  {user_id: 11, question_id: 15, option_id: 36},
  {user_id: 11, question_id: 16, option_id: 39},
  {user_id: 11, question_id: 17, option_id: 41},
  {user_id: 15, question_id: 1, option_id: 3},
  {user_id: 15, question_id: 2, option_id: 4},
  {user_id: 15, question_id: 3, option_id: 7},
  {user_id: 15, question_id: 4, option_id: 8},
  {user_id: 15, question_id: 5, option_id: 12},
  {user_id: 15, question_id: 6, option_id: 15},
  {user_id: 15, question_id: 7, option_id: 20},
  {user_id: 15, question_id: 8, option_id: 21},
  {user_id: 15, question_id: 9, option_id: 23},
  {user_id: 15, question_id: 10, option_id: 25},
  {user_id: 15, question_id: 11, option_id: 27},
  {user_id: 15, question_id: 12, option_id: 29},
  {user_id: 15, question_id: 13, option_id: 31},
  {user_id: 15, question_id: 14, option_id: 34},
  {user_id: 15, question_id: 15, option_id: 36},
  {user_id: 15, question_id: 16, option_id: 38},
  {user_id: 15, question_id: 17, option_id: 41},
  {user_id: 12, question_id: 1, option_id: 3},
  {user_id: 12, question_id: 2, option_id: 5},
  {user_id: 12, question_id: 3, option_id: 7},
  {user_id: 12, question_id: 4, option_id: 8},
  {user_id: 12, question_id: 5, option_id: 10},
  {user_id: 12, question_id: 6, option_id: 16},
  {user_id: 12, question_id: 7, option_id: 18},
  {user_id: 12, question_id: 8, option_id: 22},
  {user_id: 12, question_id: 9, option_id: 24},
  {user_id: 12, question_id: 10, option_id: 25},
  {user_id: 12, question_id: 11, option_id: 27},
  {user_id: 12, question_id: 12, option_id: 29},
  {user_id: 12, question_id: 13, option_id: 32},
  {user_id: 12, question_id: 14, option_id: 33},
  {user_id: 12, question_id: 15, option_id: 35},
  {user_id: 12, question_id: 16, option_id: 39},
  {user_id: 12, question_id: 17, option_id: 41},
  {user_id: 13, question_id: 1, option_id: 2},
  {user_id: 13, question_id: 2, option_id: 4},
  {user_id: 13, question_id: 3, option_id: 7},
  {user_id: 13, question_id: 4, option_id: 8},
  {user_id: 13, question_id: 5, option_id: 12},
  {user_id: 13, question_id: 6, option_id: 16},
  {user_id: 13, question_id: 7, option_id: 18},
  {user_id: 13, question_id: 8, option_id: 22},
  {user_id: 13, question_id: 9, option_id: 24},
  {user_id: 13, question_id: 10, option_id: 25},
  {user_id: 13, question_id: 11, option_id: 28},
  {user_id: 13, question_id: 12, option_id: 30},
  {user_id: 13, question_id: 13, option_id: 31},
  {user_id: 13, question_id: 14, option_id: 33},
  {user_id: 13, question_id: 15, option_id: 36},
  {user_id: 13, question_id: 16, option_id: 37},
  {user_id: 13, question_id: 17, option_id: 42},
  {user_id: 14, question_id: 1, option_id: 2},
  {user_id: 14, question_id: 2, option_id: 5},
  {user_id: 14, question_id: 3, option_id: 7},
  {user_id: 14, question_id: 4, option_id: 8},
  {user_id: 14, question_id: 5, option_id: 10},
  {user_id: 14, question_id: 6, option_id: 14},
  {user_id: 14, question_id: 7, option_id: 19},
  {user_id: 14, question_id: 8, option_id: 21},
  {user_id: 14, question_id: 9, option_id: 23},
  {user_id: 14, question_id: 10, option_id: 25},
  {user_id: 14, question_id: 11, option_id: 28},
  {user_id: 14, question_id: 12, option_id: 29},
  {user_id: 14, question_id: 13, option_id: 31},
  {user_id: 14, question_id: 14, option_id: 34},
  {user_id: 14, question_id: 15, option_id: 35},
  {user_id: 14, question_id: 16, option_id: 39},
  {user_id: 14, question_id: 17, option_id: 41},
  {user_id: 16, question_id: 1, option_id: 2},
  {user_id: 16, question_id: 2, option_id: 4},
  {user_id: 16, question_id: 3, option_id: 7},
  {user_id: 16, question_id: 4, option_id: 8},
  {user_id: 16, question_id: 5, option_id: 10},
  {user_id: 16, question_id: 6, option_id: 16},
  {user_id: 16, question_id: 7, option_id: 17},
  {user_id: 16, question_id: 8, option_id: 22},
  {user_id: 16, question_id: 9, option_id: 23},
  {user_id: 16, question_id: 10, option_id: 26},
  {user_id: 16, question_id: 11, option_id: 27},
  {user_id: 16, question_id: 12, option_id: 29},
  {user_id: 16, question_id: 13, option_id: 32},
  {user_id: 16, question_id: 14, option_id: 34},
  {user_id: 16, question_id: 15, option_id: 36},
  {user_id: 16, question_id: 16, option_id: 37},
  {user_id: 16, question_id: 17, option_id: 40},
  {user_id: 19, question_id: 1, option_id: 2},
  {user_id: 19, question_id: 2, option_id: 4},
  {user_id: 19, question_id: 3, option_id: 6},
  {user_id: 19, question_id: 4, option_id: 8},
  {user_id: 19, question_id: 5, option_id: 10},
  {user_id: 19, question_id: 6, option_id: 14},
  {user_id: 19, question_id: 7, option_id: 20},
  {user_id: 19, question_id: 8, option_id: 21},
  {user_id: 19, question_id: 9, option_id: 24},
  {user_id: 19, question_id: 10, option_id: 26},
  {user_id: 19, question_id: 11, option_id: 27},
  {user_id: 19, question_id: 12, option_id: 30},
  {user_id: 19, question_id: 13, option_id: 31},
  {user_id: 19, question_id: 14, option_id: 34},
  {user_id: 19, question_id: 15, option_id: 36},
  {user_id: 19, question_id: 16, option_id: 38},
  {user_id: 19, question_id: 17, option_id: 41},
  {user_id: 17, question_id: 1, option_id: 1},
  {user_id: 17, question_id: 2, option_id: 5},
  {user_id: 17, question_id: 3, option_id: 7},
  {user_id: 17, question_id: 4, option_id: 8},
  {user_id: 17, question_id: 5, option_id: 13},
  {user_id: 17, question_id: 6, option_id: 15},
  {user_id: 17, question_id: 7, option_id: 18},
  {user_id: 17, question_id: 8, option_id: 21},
  {user_id: 17, question_id: 9, option_id: 24},
  {user_id: 17, question_id: 10, option_id: 26},
  {user_id: 17, question_id: 11, option_id: 28},
  {user_id: 17, question_id: 12, option_id: 29},
  {user_id: 17, question_id: 13, option_id: 31},
  {user_id: 17, question_id: 14, option_id: 34},
  {user_id: 17, question_id: 15, option_id: 35},
  {user_id: 17, question_id: 16, option_id: 37},
  {user_id: 17, question_id: 17, option_id: 42},
  {user_id: 18, question_id: 1, option_id: 1},
  {user_id: 18, question_id: 2, option_id: 5},
  {user_id: 18, question_id: 3, option_id: 7},
  {user_id: 18, question_id: 4, option_id: 8},
  {user_id: 18, question_id: 5, option_id: 10},
  {user_id: 18, question_id: 6, option_id: 14},
  {user_id: 18, question_id: 7, option_id: 18},
  {user_id: 18, question_id: 8, option_id: 22},
  {user_id: 18, question_id: 9, option_id: 24},
  {user_id: 18, question_id: 10, option_id: 25},
  {user_id: 18, question_id: 11, option_id: 27},
  {user_id: 18, question_id: 12, option_id: 30},
  {user_id: 18, question_id: 13, option_id: 32},
  {user_id: 18, question_id: 14, option_id: 34},
  {user_id: 18, question_id: 15, option_id: 35},
  {user_id: 18, question_id: 16, option_id: 37},
  {user_id: 18, question_id: 17, option_id: 40},
  {user_id: 20, question_id: 1, option_id: 1},
  {user_id: 20, question_id: 2, option_id: 4},
  {user_id: 20, question_id: 3, option_id: 7},
  {user_id: 20, question_id: 4, option_id: 8},
  {user_id: 20, question_id: 5, option_id: 11},
  {user_id: 20, question_id: 6, option_id: 16},
  {user_id: 20, question_id: 7, option_id: 17},
  {user_id: 20, question_id: 8, option_id: 21},
  {user_id: 20, question_id: 9, option_id: 24},
  {user_id: 20, question_id: 10, option_id: 26},
  {user_id: 20, question_id: 11, option_id: 28},
  {user_id: 20, question_id: 12, option_id: 29},
  {user_id: 20, question_id: 13, option_id: 32},
  {user_id: 20, question_id: 14, option_id: 33},
  {user_id: 20, question_id: 15, option_id: 35},
  {user_id: 20, question_id: 16, option_id: 37},
  {user_id: 20, question_id: 17, option_id: 41},
  {user_id: 21, question_id: 1, option_id: 3},
  {user_id: 21, question_id: 2, option_id: 4},
  {user_id: 21, question_id: 3, option_id: 6},
  {user_id: 21, question_id: 4, option_id: 9},
  {user_id: 21, question_id: 5, option_id: 11},
  {user_id: 21, question_id: 6, option_id: 15},
  {user_id: 21, question_id: 7, option_id: 19},
  {user_id: 21, question_id: 8, option_id: 21},
  {user_id: 21, question_id: 9, option_id: 24},
  {user_id: 21, question_id: 10, option_id: 25},
  {user_id: 21, question_id: 11, option_id: 28},
  {user_id: 21, question_id: 12, option_id: 30},
  {user_id: 21, question_id: 13, option_id: 32},
  {user_id: 21, question_id: 14, option_id: 34},
  {user_id: 21, question_id: 15, option_id: 36},
  {user_id: 21, question_id: 16, option_id: 37},
  {user_id: 21, question_id: 17, option_id: 41},
  {user_id: 22, question_id: 1, option_id: 3},
  {user_id: 22, question_id: 2, option_id: 4},
  {user_id: 22, question_id: 3, option_id: 6},
  {user_id: 22, question_id: 4, option_id: 9},
  {user_id: 22, question_id: 5, option_id: 12},
  {user_id: 22, question_id: 6, option_id: 14},
  {user_id: 22, question_id: 7, option_id: 17},
  {user_id: 22, question_id: 8, option_id: 21},
  {user_id: 22, question_id: 9, option_id: 24},
  {user_id: 22, question_id: 10, option_id: 25},
  {user_id: 22, question_id: 11, option_id: 27},
  {user_id: 22, question_id: 12, option_id: 30},
  {user_id: 22, question_id: 13, option_id: 32},
  {user_id: 22, question_id: 14, option_id: 34},
  {user_id: 22, question_id: 15, option_id: 36},
  {user_id: 22, question_id: 16, option_id: 38},
  {user_id: 22, question_id: 17, option_id: 41},
  {user_id: 23, question_id: 1, option_id: 3},
  {user_id: 23, question_id: 2, option_id: 5},
  {user_id: 23, question_id: 3, option_id: 6},
  {user_id: 23, question_id: 4, option_id: 9},
  {user_id: 23, question_id: 5, option_id: 10},
  {user_id: 23, question_id: 6, option_id: 15},
  {user_id: 23, question_id: 7, option_id: 18},
  {user_id: 23, question_id: 8, option_id: 22},
  {user_id: 23, question_id: 9, option_id: 24},
  {user_id: 23, question_id: 10, option_id: 25},
  {user_id: 23, question_id: 11, option_id: 28},
  {user_id: 23, question_id: 12, option_id: 30},
  {user_id: 23, question_id: 13, option_id: 31},
  {user_id: 23, question_id: 14, option_id: 33},
  {user_id: 23, question_id: 15, option_id: 35},
  {user_id: 23, question_id: 16, option_id: 39},
  {user_id: 23, question_id: 17, option_id: 41},
  {user_id: 24, question_id: 1, option_id: 2},
  {user_id: 24, question_id: 2, option_id: 5},
  {user_id: 24, question_id: 3, option_id: 7},
  {user_id: 24, question_id: 4, option_id: 9},
  {user_id: 24, question_id: 5, option_id: 10},
  {user_id: 24, question_id: 6, option_id: 16},
  {user_id: 24, question_id: 7, option_id: 19},
  {user_id: 24, question_id: 8, option_id: 21},
  {user_id: 24, question_id: 9, option_id: 23},
  {user_id: 24, question_id: 10, option_id: 25},
  {user_id: 24, question_id: 11, option_id: 27},
  {user_id: 24, question_id: 12, option_id: 30},
  {user_id: 24, question_id: 13, option_id: 31},
  {user_id: 24, question_id: 14, option_id: 33},
  {user_id: 24, question_id: 15, option_id: 35},
  {user_id: 24, question_id: 16, option_id: 39},
  {user_id: 24, question_id: 17, option_id: 40},
  {user_id: 25, question_id: 1, option_id: 2},
  {user_id: 25, question_id: 2, option_id: 5},
  {user_id: 25, question_id: 3, option_id: 6},
  {user_id: 25, question_id: 4, option_id: 8},
  {user_id: 25, question_id: 5, option_id: 12},
  {user_id: 25, question_id: 6, option_id: 14},
  {user_id: 25, question_id: 7, option_id: 18},
  {user_id: 25, question_id: 8, option_id: 21},
  {user_id: 25, question_id: 9, option_id: 23},
  {user_id: 25, question_id: 10, option_id: 25},
  {user_id: 25, question_id: 11, option_id: 27},
  {user_id: 25, question_id: 12, option_id: 30},
  {user_id: 25, question_id: 13, option_id: 31},
  {user_id: 25, question_id: 14, option_id: 33},
  {user_id: 25, question_id: 15, option_id: 35},
  {user_id: 25, question_id: 16, option_id: 38},
  {user_id: 25, question_id: 17, option_id: 40},
  {user_id: 26, question_id: 1, option_id: 3},
  {user_id: 26, question_id: 2, option_id: 5},
  {user_id: 26, question_id: 3, option_id: 6},
  {user_id: 26, question_id: 4, option_id: 9},
  {user_id: 26, question_id: 5, option_id: 12},
  {user_id: 26, question_id: 6, option_id: 15},
  {user_id: 26, question_id: 7, option_id: 19},
  {user_id: 26, question_id: 8, option_id: 22},
  {user_id: 26, question_id: 9, option_id: 24},
  {user_id: 26, question_id: 10, option_id: 25},
  {user_id: 26, question_id: 11, option_id: 27},
  {user_id: 26, question_id: 12, option_id: 29},
  {user_id: 26, question_id: 13, option_id: 31},
  {user_id: 26, question_id: 14, option_id: 33},
  {user_id: 26, question_id: 15, option_id: 36},
  {user_id: 26, question_id: 16, option_id: 37},
  {user_id: 26, question_id: 17, option_id: 41},
  {user_id: 27, question_id: 1, option_id: 3},
  {user_id: 27, question_id: 2, option_id: 4},
  {user_id: 27, question_id: 3, option_id: 7},
  {user_id: 27, question_id: 4, option_id: 8},
  {user_id: 27, question_id: 5, option_id: 13},
  {user_id: 27, question_id: 6, option_id: 16},
  {user_id: 27, question_id: 7, option_id: 17},
  {user_id: 27, question_id: 8, option_id: 21},
  {user_id: 27, question_id: 9, option_id: 23},
  {user_id: 27, question_id: 10, option_id: 25},
  {user_id: 27, question_id: 11, option_id: 28},
  {user_id: 27, question_id: 12, option_id: 29},
  {user_id: 27, question_id: 13, option_id: 31},
  {user_id: 27, question_id: 14, option_id: 34},
  {user_id: 27, question_id: 15, option_id: 36},
  {user_id: 27, question_id: 16, option_id: 39},
  {user_id: 27, question_id: 17, option_id: 42},
  {user_id: 28, question_id: 1, option_id: 3},
  {user_id: 28, question_id: 2, option_id: 4},
  {user_id: 28, question_id: 3, option_id: 6},
  {user_id: 28, question_id: 4, option_id: 9},
  {user_id: 28, question_id: 5, option_id: 12},
  {user_id: 28, question_id: 6, option_id: 14},
  {user_id: 28, question_id: 7, option_id: 20},
  {user_id: 28, question_id: 8, option_id: 21},
  {user_id: 28, question_id: 9, option_id: 24},
  {user_id: 28, question_id: 10, option_id: 25},
  {user_id: 28, question_id: 11, option_id: 27},
  {user_id: 28, question_id: 12, option_id: 30},
  {user_id: 28, question_id: 13, option_id: 32},
  {user_id: 28, question_id: 14, option_id: 33},
  {user_id: 28, question_id: 15, option_id: 36},
  {user_id: 28, question_id: 16, option_id: 37},
  {user_id: 28, question_id: 17, option_id: 40},
  {user_id: 29, question_id: 1, option_id: 3},
  {user_id: 29, question_id: 2, option_id: 5},
  {user_id: 29, question_id: 3, option_id: 6},
  {user_id: 29, question_id: 4, option_id: 8},
  {user_id: 29, question_id: 5, option_id: 11},
  {user_id: 29, question_id: 6, option_id: 16},
  {user_id: 29, question_id: 7, option_id: 17},
  {user_id: 29, question_id: 8, option_id: 22},
  {user_id: 29, question_id: 9, option_id: 24},
  {user_id: 29, question_id: 10, option_id: 25},
  {user_id: 29, question_id: 11, option_id: 27},
  {user_id: 29, question_id: 12, option_id: 29},
  {user_id: 29, question_id: 13, option_id: 31},
  {user_id: 29, question_id: 14, option_id: 34},
  {user_id: 29, question_id: 15, option_id: 36},
  {user_id: 29, question_id: 16, option_id: 38},
  {user_id: 29, question_id: 17, option_id: 42},
  {user_id: 30, question_id: 1, option_id: 3},
  {user_id: 30, question_id: 2, option_id: 4},
  {user_id: 30, question_id: 3, option_id: 6},
  {user_id: 30, question_id: 4, option_id: 9},
  {user_id: 30, question_id: 5, option_id: 10},
  {user_id: 30, question_id: 6, option_id: 15},
  {user_id: 30, question_id: 7, option_id: 19},
  {user_id: 30, question_id: 8, option_id: 22},
  {user_id: 30, question_id: 9, option_id: 23},
  {user_id: 30, question_id: 10, option_id: 26},
  {user_id: 30, question_id: 11, option_id: 28},
  {user_id: 30, question_id: 12, option_id: 29},
  {user_id: 30, question_id: 13, option_id: 31},
  {user_id: 30, question_id: 14, option_id: 34},
  {user_id: 30, question_id: 15, option_id: 36},
  {user_id: 30, question_id: 16, option_id: 38},
  {user_id: 30, question_id: 17, option_id: 41},
  {user_id: 31, question_id: 1, option_id: 1},
  {user_id: 31, question_id: 2, option_id: 5},
  {user_id: 31, question_id: 3, option_id: 6},
  {user_id: 31, question_id: 4, option_id: 8},
  {user_id: 31, question_id: 5, option_id: 11},
  {user_id: 31, question_id: 6, option_id: 16},
  {user_id: 31, question_id: 7, option_id: 20},
  {user_id: 31, question_id: 8, option_id: 21},
  {user_id: 31, question_id: 9, option_id: 23},
  {user_id: 31, question_id: 10, option_id: 25},
  {user_id: 31, question_id: 11, option_id: 27},
  {user_id: 31, question_id: 12, option_id: 29},
  {user_id: 31, question_id: 14, option_id: 33},
  {user_id: 31, question_id: 15, option_id: 35},
  {user_id: 31, question_id: 16, option_id: 38},
  {user_id: 31, question_id: 17, option_id: 40},
  {user_id: 32, question_id: 1, option_id: 1},
  {user_id: 31, question_id: 13, option_id: 32},
  {user_id: 32, question_id: 3, option_id: 7},
  {user_id: 32, question_id: 4, option_id: 9},
  {user_id: 32, question_id: 5, option_id: 13},
  {user_id: 32, question_id: 6, option_id: 15},
  {user_id: 32, question_id: 7, option_id: 18},
  {user_id: 32, question_id: 8, option_id: 22},
  {user_id: 32, question_id: 9, option_id: 24},
  {user_id: 32, question_id: 10, option_id: 26},
  {user_id: 32, question_id: 11, option_id: 27},
  {user_id: 32, question_id: 12, option_id: 30},
  {user_id: 32, question_id: 13, option_id: 31},
  {user_id: 32, question_id: 14, option_id: 34},
  {user_id: 32, question_id: 15, option_id: 35},
  {user_id: 32, question_id: 16, option_id: 37},
  {user_id: 32, question_id: 17, option_id: 42},
  {user_id: 33, question_id: 1, option_id: 1},
  {user_id: 33, question_id: 2, option_id: 4},
  {user_id: 33, question_id: 3, option_id: 7},
  {user_id: 33, question_id: 4, option_id: 9},
  {user_id: 33, question_id: 5, option_id: 11},
  {user_id: 33, question_id: 6, option_id: 16},
  {user_id: 33, question_id: 7, option_id: 20},
  {user_id: 33, question_id: 8, option_id: 21},
  {user_id: 33, question_id: 9, option_id: 24},
  {user_id: 33, question_id: 10, option_id: 25},
  {user_id: 33, question_id: 11, option_id: 27},
  {user_id: 33, question_id: 12, option_id: 30},
  {user_id: 33, question_id: 13, option_id: 32},
  {user_id: 33, question_id: 14, option_id: 33},
  {user_id: 33, question_id: 15, option_id: 36},
  {user_id: 33, question_id: 16, option_id: 38},
  {user_id: 33, question_id: 17, option_id: 41},
  {user_id: 34, question_id: 1, option_id: 2},
  {user_id: 32, question_id: 2, option_id: 4},
  {user_id: 34, question_id: 2, option_id: 4},
  {user_id: 34, question_id: 3, option_id: 6},
  {user_id: 34, question_id: 4, option_id: 8},
  {user_id: 34, question_id: 5, option_id: 12},
  {user_id: 34, question_id: 6, option_id: 14},
  {user_id: 34, question_id: 7, option_id: 18},
  {user_id: 34, question_id: 8, option_id: 22},
  {user_id: 34, question_id: 9, option_id: 24},
  {user_id: 34, question_id: 10, option_id: 26},
  {user_id: 34, question_id: 11, option_id: 28},
  {user_id: 34, question_id: 12, option_id: 30},
  {user_id: 34, question_id: 13, option_id: 32},
  {user_id: 34, question_id: 14, option_id: 33},
  {user_id: 34, question_id: 15, option_id: 36},
  {user_id: 34, question_id: 16, option_id: 38},
  {user_id: 34, question_id: 17, option_id: 42},
  {user_id: 2, question_id: 11, option_id: 27},
  {user_id: 2, question_id: 13, option_id: 32}
])
AnswerOption.create!([
  {question_id: 1, body: "The Sun"},
  {question_id: 1, body: "The Earth"},
  {question_id: 1, body: "Me"},
  {question_id: 2, body: "Yes"},
  {question_id: 2, body: "No"},
  {question_id: 3, body: "Yes"},
  {question_id: 3, body: "No"},
  {question_id: 4, body: "Yes"},
  {question_id: 4, body: "No"},
  {question_id: 5, body: "Cat"},
  {question_id: 5, body: "Dog"},
  {question_id: 5, body: "Both"},
  {question_id: 5, body: "Neither"},
  {question_id: 6, body: "Vegetarian"},
  {question_id: 6, body: "Vegan"},
  {question_id: 6, body: "Neither"},
  {question_id: 7, body: "Love"},
  {question_id: 7, body: "Wealth"},
  {question_id: 7, body: "Expression"},
  {question_id: 7, body: "Knowledge"},
  {question_id: 8, body: "Good"},
  {question_id: 8, body: "Bad"},
  {question_id: 9, body: "Yes"},
  {question_id: 9, body: "No"},
  {question_id: 10, body: "Yes"},
  {question_id: 10, body: "No"},
  {question_id: 11, body: "Yes"},
  {question_id: 11, body: "No"},
  {question_id: 12, body: "Yes"},
  {question_id: 12, body: "No"},
  {question_id: 13, body: "Yes"},
  {question_id: 13, body: "No"},
  {question_id: 14, body: "Yes"},
  {question_id: 14, body: "No"},
  {question_id: 15, body: "Yes"},
  {question_id: 15, body: "No"},
  {question_id: 16, body: "Very inclined"},
  {question_id: 16, body: "Somewhat inclined"},
  {question_id: 16, body: "Not inclined"},
  {question_id: 17, body: "Admirable and desirable. Chivalry's not dead."},
  {question_id: 17, body: "Unnecessary but appreciated."},
  {question_id: 17, body: "Sexist and insulting; women are perfectly capable."}
])
Essay.create!([
  {user_id: 1, title: "Favorite Pokemon", body: "Meowth"},
  {user_id: 1, title: "Favorite Chuck Norris fact", body: "Chuck Norris can binary search unsorted data."},
  {user_id: 1, title: "Favorite Star Wars quote", body: "Wars not make one great."},
  {user_id: 1, title: "My superhero name and power", body: "Bushido, with the power of Sub-Mariner"},
  {user_id: 1, title: "I would love to...", body: "enhance e-business eyeballs"},
  {user_id: 2, title: "Favorite Pokemon", body: "Kangaskhan"},
  {user_id: 2, title: "Favorite Chuck Norris fact", body: "When Chuck Norris presses Ctrl+Alt+Delete, worldwide computer restart is initiated."},
  {user_id: 2, title: "Favorite Star Wars quote", body: "Truly wonderful, the mind of a child is."},
  {user_id: 2, title: "My superhero name and power", body: "Etrigan Brain, with the power of Telepathy Resistance"},
  {user_id: 2, title: "I would love to...", body: "monetize revolutionary communities"},
  {user_id: 3, title: "Favorite Pokemon", body: "Magikarp"},
  {user_id: 3, title: "Favorite Chuck Norris fact", body: "For Chuck Norris, NP-Hard = O(1)."},
  {user_id: 3, title: "Favorite Star Wars quote", body: "Adventure. Excitement. A Jedi craves not these things."},
  {user_id: 3, title: "My superhero name and power", body: "Ammo Woman, with the power of Astral Trap"},
  {user_id: 3, title: "I would love to...", body: "disintermediate 24/365 applications"},
  {user_id: 4, title: "Favorite Pokemon", body: "Muk"},
  {user_id: 4, title: "Favorite Chuck Norris fact", body: "There is nothing regular about Chuck Norris' expressions."},
  {user_id: 4, title: "Favorite Star Wars quote", body: "Only at the end do you realize the power of the Dark Side."},
  {user_id: 4, title: "My superhero name and power", body: "Giant Aztar, with the power of Matter Absorption"},
  {user_id: 4, title: "I would love to...", body: "redefine sticky platforms"},
  {user_id: 5, title: "Favorite Pokemon", body: "Horsea"},
  {user_id: 5, title: "Favorite Chuck Norris fact", body: "Whiteboards are white because Chuck Norris scared them that way."},
  {user_id: 5, title: "Favorite Star Wars quote", body: "That is why you fail."},
  {user_id: 5, title: "My superhero name and power", body: "Supah Molten Man of Hearts, with the power of Radiation Control"},
  {user_id: 5, title: "I would love to...", body: "harness cutting-edge bandwidth"},
  {user_id: 6, title: "Favorite Pokemon", body: "Arcanine"},
  {user_id: 6, title: "Favorite Chuck Norris fact", body: "Chuck Norris can recite π. Backwards."},
  {user_id: 6, title: "Favorite Star Wars quote", body: "Shut him up or shut him down."},
  {user_id: 6, title: "My superhero name and power", body: "Quantum, with the power of Jump"},
  {user_id: 6, title: "I would love to...", body: "disintermediate vertical models"},
  {user_id: 7, title: "Favorite Pokemon", body: "Onix"},
  {user_id: 7, title: "Favorite Chuck Norris fact", body: "Chuck Norris can compile syntax errors."},
  {user_id: 7, title: "Favorite Star Wars quote", body: "Fear is the path to the dark side... fear leads to anger... anger leads to hate... hate leads to suffering."},
  {user_id: 7, title: "My superhero name and power", body: "Watcher Eyes, with the power of Psionic Powers"},
  {user_id: 7, title: "I would love to...", body: "grow cross-platform content"},
  {user_id: 8, title: "Favorite Pokemon", body: "Magnemite"},
  {user_id: 8, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't delete files, he blows them away."},
  {user_id: 8, title: "Favorite Star Wars quote", body: "Strike me down, and I will become more powerful than you could possibly imagine."},
  {user_id: 8, title: "My superhero name and power", body: "Mockingbird, with the power of Toxikinesis"},
  {user_id: 8, title: "I would love to...", body: "facilitate customized web services"},
  {user_id: 10, title: "Favorite Pokemon", body: "Machoke"},
  {user_id: 10, title: "Favorite Chuck Norris fact", body: "Chuck Norris does not use revision control software. None of his code has ever needed revision."},
  {user_id: 10, title: "Favorite Star Wars quote", body: "I have a bad feeling about this."},
  {user_id: 10, title: "My superhero name and power", body: "Doctor Morph Eyes, with the power of Teleportation"},
  {user_id: 10, title: "I would love to...", body: "extend dynamic networks"},
  {user_id: 11, title: "Favorite Pokemon", body: "Nidoran"},
  {user_id: 11, title: "Favorite Chuck Norris fact", body: "Quantum cryptography does not work on Chuck Norris. When something is being observed by Chuck it stays in the same state until he's finished. "},
  {user_id: 11, title: "Favorite Star Wars quote", body: "If they follow standard Imperial procedure, they'll dump their garbage before they go to light-speed."},
  {user_id: 11, title: "My superhero name and power", body: "Cyborg Gambit Fist, with the power of Density Control"},
  {user_id: 11, title: "I would love to...", body: "scale sticky platforms"},
  {user_id: 12, title: "Favorite Pokemon", body: "Ivysaur"},
  {user_id: 12, title: "Favorite Chuck Norris fact", body: "\"It works on my machine\" always holds true for Chuck Norris."},
  {user_id: 12, title: "Favorite Star Wars quote", body: "Do. Or do not. There is no try."},
  {user_id: 12, title: "My superhero name and power", body: "Galactus of Hearts, with the power of Vision - Thermal"},
  {user_id: 12, title: "I would love to...", body: "iterate compelling e-commerce"},
  {user_id: 13, title: "Favorite Pokemon", body: "Mankey"},
  {user_id: 13, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't need the cloud to scale his applications, he uses his laptop."},
  {user_id: 13, title: "Favorite Star Wars quote", body: "Strike me down, and I will become more powerful than you could possibly imagine."},
  {user_id: 13, title: "My superhero name and power", body: "Nova, with the power of Hypnokinesis"},
  {user_id: 13, title: "I would love to...", body: "incubate mission-critical niches"},
  {user_id: 14, title: "Favorite Pokemon", body: "Omastar"},
  {user_id: 14, title: "Favorite Chuck Norris fact", body: "Chuck Norris is immutable. If something's going to change, it's going to have to be the rest of the universe."},
  {user_id: 14, title: "Favorite Star Wars quote", body: "Now, witness the power of this fully operational battle station."},
  {user_id: 14, title: "My superhero name and power", body: "Giant Shriek, with the power of Lantern Power Ring"},
  {user_id: 14, title: "I would love to...", body: "redefine wireless content"},
  {user_id: 15, title: "Favorite Pokemon", body: "Nidoran"},
  {user_id: 15, title: "Favorite Chuck Norris fact", body: "Chuck Norris can compile syntax errors."},
  {user_id: 15, title: "Favorite Star Wars quote", body: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters."},
  {user_id: 15, title: "My superhero name and power", body: "Illustrious Goku Strike, with the power of Substance Secretion"},
  {user_id: 15, title: "I would love to...", body: "transform best-of-breed initiatives"},
  {user_id: 16, title: "Favorite Pokemon", body: "Gloom"},
  {user_id: 16, title: "Favorite Chuck Norris fact", body: "Chuck Norris can solve the Towers of Hanoi in one move."},
  {user_id: 16, title: "Favorite Star Wars quote", body: "I find your lack of faith disturbing."},
  {user_id: 16, title: "My superhero name and power", body: "Sobek, with the power of Power Sense"},
  {user_id: 16, title: "I would love to...", body: "strategize virtual partnerships"},
  {user_id: 17, title: "Favorite Pokemon", body: "Kakuna"},
  {user_id: 17, title: "Favorite Chuck Norris fact", body: "Chuck Norris can write multi-threaded applications with a single thread."},
  {user_id: 17, title: "Favorite Star Wars quote", body: "If they follow standard Imperial procedure, they'll dump their garbage before they go to light-speed."},
  {user_id: 17, title: "My superhero name and power", body: "Magnificent Firestorm Spirit, with the power of Timeframe Control"},
  {user_id: 17, title: "I would love to...", body: "harness value-added applications"},
  {user_id: 18, title: "Favorite Pokemon", body: "Omastar"},
  {user_id: 18, title: "Favorite Chuck Norris fact", body: "All arrays Chuck Norris declares are of infinite size, because Chuck Norris knows no bounds."},
  {user_id: 18, title: "Favorite Star Wars quote", body: "You'll find I'm full of surprises!"},
  {user_id: 18, title: "My superhero name and power", body: "Falcon, with the power of Aerokinesis"},
  {user_id: 18, title: "I would love to...", body: "scale end-to-end interfaces"},
  {user_id: 19, title: "Favorite Pokemon", body: "Weezing"},
  {user_id: 19, title: "Favorite Chuck Norris fact", body: "Chuck Norris rewrote the Google search engine from scratch."},
  {user_id: 19, title: "Favorite Star Wars quote", body: "That is why you fail."},
  {user_id: 19, title: "My superhero name and power", body: "Joker, with the power of Empathy"},
  {user_id: 19, title: "I would love to...", body: "productize revolutionary architectures"},
  {user_id: 20, title: "Favorite Pokemon", body: "Gyarados"},
  {user_id: 20, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't bug hunt, as that signifies a probability of failure. He goes bug killing."},
  {user_id: 20, title: "Favorite Star Wars quote", body: "R2-D2, you know better than to trust a strange computer!"},
  {user_id: 20, title: "My superhero name and power", body: "Cottonmouth, with the power of Fire Resistance"},
  {user_id: 20, title: "I would love to...", body: "scale intuitive action-items"},
  {user_id: 21, title: "Favorite Pokemon", body: "Slowpoke"},
  {user_id: 21, title: "Favorite Chuck Norris fact", body: "The programs that Chuck Norris writes don't have version numbers because he only writes them once. If a user reports a bug or has a feature request they don't live to see the sun set."},
  {user_id: 21, title: "Favorite Star Wars quote", body: "I have a bad feeling about this."},
  {user_id: 21, title: "My superhero name and power", body: "Skaar Wolf, with the power of Mind Control"},
  {user_id: 21, title: "I would love to...", body: "aggregate customized e-services"},
  {user_id: 22, title: "Favorite Pokemon", body: "Machamp"},
  {user_id: 22, title: "Favorite Chuck Norris fact", body: "You don't disable the Chuck Norris plug-in, it disables you."},
  {user_id: 22, title: "Favorite Star Wars quote", body: "Who's the more foolish; the fool, or the fool who follows him?"},
  {user_id: 22, title: "My superhero name and power", body: "Captain Doppelganger, with the power of Animation"},
  {user_id: 22, title: "I would love to...", body: "utilize real-time action-items"},
  {user_id: 23, title: "Favorite Pokemon", body: "Poliwhirl"},
  {user_id: 23, title: "Favorite Chuck Norris fact", body: "Chuck Norris programs do not accept input."},
  {user_id: 23, title: "Favorite Star Wars quote", body: "You'll find I'm full of surprises!"},
  {user_id: 23, title: "My superhero name and power", body: "Doctor Bullseye, with the power of Dexterity"},
  {user_id: 23, title: "I would love to...", body: "empower world-class content"},
  {user_id: 24, title: "Favorite Pokemon", body: "Dodrio"},
  {user_id: 24, title: "Favorite Chuck Norris fact", body: "Chuck Norris does not use revision control software. None of his code has ever needed revision."},
  {user_id: 24, title: "Favorite Star Wars quote", body: "You will never find a more wretched hive of scum and villainy. We must be cautious."},
  {user_id: 24, title: "My superhero name and power", body: "General Wiz Kid, with the power of Orbing"},
  {user_id: 24, title: "I would love to...", body: "target innovative e-markets"},
  {user_id: 25, title: "Favorite Pokemon", body: "Goldeen"},
  {user_id: 25, title: "Favorite Chuck Norris fact", body: "Chuck Norris can access private methods."},
  {user_id: 25, title: "Favorite Star Wars quote", body: "I have a bad feeling about this."},
  {user_id: 25, title: "My superhero name and power", body: "Red Copycat Thirteen, with the power of Magic"},
  {user_id: 25, title: "I would love to...", body: "iterate granular users"},
  {user_id: 26, title: "Favorite Pokemon", body: "Sandslash"},
  {user_id: 26, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't program with a keyboard. He stares the computer down until it does what he wants."},
  {user_id: 26, title: "Favorite Star Wars quote", body: "You do have your moments. Not many, but you have them."},
  {user_id: 26, title: "My superhero name and power", body: "Justice Skull, with the power of Danger Sense"},
  {user_id: 26, title: "I would love to...", body: "transform frictionless initiatives"},
  {user_id: 27, title: "Favorite Pokemon", body: "Gastly"},
  {user_id: 27, title: "Favorite Chuck Norris fact", body: "Chuck Norris's first program was kill -9."},
  {user_id: 27, title: "Favorite Star Wars quote", body: "Wars not make one great."},
  {user_id: 27, title: "My superhero name and power", body: "Overtkill, with the power of Radar Sense"},
  {user_id: 27, title: "I would love to...", body: "extend bricks-and-clicks action-items"},
  {user_id: 28, title: "Favorite Pokemon", body: "Kabutops"},
  {user_id: 28, title: "Favorite Chuck Norris fact", body: "Chuck Norris' protocol design method has no status, requests or responses, only commands."},
  {user_id: 28, title: "Favorite Star Wars quote", body: "You do have your moments. Not many, but you have them."},
  {user_id: 28, title: "My superhero name and power", body: "Speedy, with the power of Enhanced Touch"},
  {user_id: 28, title: "I would love to...", body: "innovate visionary metrics"},
  {user_id: 29, title: "Favorite Pokemon", body: "Mankey"},
  {user_id: 29, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't need an OS."},
  {user_id: 29, title: "Favorite Star Wars quote", body: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters."},
  {user_id: 29, title: "My superhero name and power", body: "Predator of Hearts, with the power of Reality Warping"},
  {user_id: 29, title: "I would love to...", body: "reinvent mission-critical e-markets"},
  {user_id: 30, title: "Favorite Pokemon", body: "Drowzee"},
  {user_id: 30, title: "Favorite Chuck Norris fact", body: "Chuck Norris's keyboard doesn't have a Ctrl key because nothing controls Chuck Norris."},
  {user_id: 30, title: "Favorite Star Wars quote", body: "It's not impossible. I used to bullseye womp rats in my T-16 back home, they're not much bigger than two meters."},
  {user_id: 30, title: "My superhero name and power", body: "Jigsaw, with the power of Accuracy"},
  {user_id: 30, title: "I would love to...", body: "whiteboard leading-edge initiatives"},
  {user_id: 31, title: "Favorite Pokemon", body: "Magmar"},
  {user_id: 31, title: "Favorite Chuck Norris fact", body: "When a bug sees Chuck Norris, it flees screaming in terror, and then immediately self-destructs to avoid being roundhouse-kicked."},
  {user_id: 31, title: "Favorite Star Wars quote", body: "Well, you said you wanted to be around when I made a mistake."},
  {user_id: 31, title: "My superhero name and power", body: "Green Destroyer Spirit, with the power of Electrokinesis"},
  {user_id: 31, title: "I would love to...", body: "cultivate frictionless functionalities"},
  {user_id: 32, title: "Favorite Pokemon", body: "Voltorb"},
  {user_id: 32, title: "Favorite Chuck Norris fact", body: "For Chuck Norris, NP-Hard = O(1)."},
  {user_id: 32, title: "Favorite Star Wars quote", body: "Aren't you a little short for a Stormtrooper?"},
  {user_id: 32, title: "My superhero name and power", body: "Dark Goliath IX, with the power of Power Sense"},
  {user_id: 32, title: "I would love to...", body: "syndicate virtual e-tailers"},
  {user_id: 33, title: "Favorite Pokemon", body: "Spearow"},
  {user_id: 33, title: "Favorite Chuck Norris fact", body: "Chuck Norris doesn't believe in floating point numbers because they can't be typed on his binary keyboard."},
  {user_id: 33, title: "Favorite Star Wars quote", body: "You do have your moments. Not many, but you have them."},
  {user_id: 33, title: "My superhero name and power", body: "Wiz Kid, with the power of Nova Force"},
  {user_id: 33, title: "I would love to...", body: "grow bleeding-edge infomediaries"},
  {user_id: 34, title: "Favorite Pokemon", body: "Arcanine"},
  {user_id: 34, title: "Favorite Chuck Norris fact", body: "Chuck Norris can write multi-threaded applications with a single thread."},
  {user_id: 34, title: "Favorite Star Wars quote", body: "If you're saying that coming here was a bad idea, I'm starting to agree with you."},
  {user_id: 34, title: "My superhero name and power", body: "Sasquatch X, with the power of Pyrokinesis"},
  {user_id: 34, title: "I would love to...", body: "enable turn-key models"},
  {user_id: 9, title: "Favorite Pokemon", body: "Pidgeotto"},
  {user_id: 9, title: "Favorite Chuck Norris fact", body: "When Chuck Norris' code fails to compile the compiler apologises."},
  {user_id: 9, title: "Favorite Star Wars quote", body: "You will never find a more wretched hive of scum and villainy. We must be cautious."},
  {user_id: 9, title: "My superhero name and power", body: "Cottonmouth Girl, with the power of Force Fields"},
  {user_id: 9, title: "I would love to...", body: "whiteboard virtual infomediaries"}
])
Filter.create!([
  {user_id: 1, gender: "female", orientation: nil, min_age: 16, max_age: 22, location: "San Diego, CA", distance: 25, postal_code: "92127", latitude: 33.0227476, longitude: -117.1382404},
  {user_id: 3, gender: "male", orientation: nil, min_age: 16, max_age: 22, location: "San Diego, CA", distance: 25, postal_code: "92127", latitude: 33.0227476, longitude: -117.1382404},
  {user_id: 4, gender: "male", orientation: nil, min_age: 16, max_age: 22, location: "San Diego, CA", distance: 25, postal_code: "92127", latitude: 33.0227476, longitude: -117.1382404},
  {user_id: 5, gender: "male", orientation: nil, min_age: 15, max_age: 20, location: "Oceanside, CA", distance: 25, postal_code: "92049", latitude: 33.1950781, longitude: -117.378631},
  {user_id: 6, gender: "male", orientation: nil, min_age: 16, max_age: 22, location: "Encinitas, CA", distance: 25, postal_code: "92023", latitude: 33.060208, longitude: -117.2657906},
  {user_id: 7, gender: "female", orientation: nil, min_age: 16, max_age: 22, location: "Del Mar, CA", distance: 25, postal_code: "92014", latitude: 32.9864215, longitude: -117.226457},
  {user_id: 8, gender: "male", orientation: nil, min_age: 14, max_age: 20, location: "Encinitas, CA", distance: 25, postal_code: "92024", latitude: 33.052083, longitude: -117.2793685},
  {user_id: 10, gender: "female", orientation: nil, min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94103", latitude: 37.7726402, longitude: -122.4099154},
  {user_id: 11, gender: "male", orientation: nil, min_age: 16, max_age: 22, location: "San Francisco, CA", distance: 25, postal_code: "94121", latitude: 37.7813454, longitude: -122.497668},
  {user_id: 12, gender: "female", orientation: nil, min_age: 16, max_age: 22, location: "San Francisco, CA", distance: 25, postal_code: "94122", latitude: 37.7597481, longitude: -122.4750292},
  {user_id: 13, gender: nil, orientation: nil, min_age: 15, max_age: 20, location: "San Francisco, CA", distance: 25, postal_code: "94116", latitude: 37.7432421, longitude: -122.497668},
  {user_id: 14, gender: nil, orientation: nil, min_age: 16, max_age: 22, location: "San Francisco, CA", distance: 25, postal_code: "94131", latitude: 37.7401042, longitude: -122.4382307},
  {user_id: 15, gender: "male", orientation: nil, min_age: 14, max_age: 20, location: "San Francisco, CA", distance: 25, postal_code: "94118", latitude: 37.7822891, longitude: -122.463708},
  {user_id: 16, gender: "female", orientation: nil, min_age: 15, max_age: 20, location: "San Francisco, CA", distance: 25, postal_code: "94118", latitude: 37.7822891, longitude: -122.463708},
  {user_id: 17, gender: nil, orientation: nil, min_age: 15, max_age: 20, location: "San Francisco, CA", distance: 25, postal_code: "94121", latitude: 37.7813454, longitude: -122.497668},
  {user_id: 18, gender: "female", orientation: "", min_age: 14, max_age: 20, location: "San Francisco, CA", distance: 25, postal_code: "94114", latitude: 37.7561438, longitude: -122.4325682},
  {user_id: 19, gender: "everyone", orientation: "", min_age: 14, max_age: 20, location: "Berkeley, CA", distance: 25, postal_code: "94710", latitude: 37.8645848, longitude: -122.2965778},
  {user_id: 20, gender: "female", orientation: nil, min_age: 14, max_age: 20, location: "Berkeley, CA", distance: 25, postal_code: "94702", latitude: 37.8680576, longitude: -122.2852374},
  {user_id: 21, gender: "male", orientation: nil, min_age: 15, max_age: 20, location: "Berkeley, CA", distance: 25, postal_code: "94710", latitude: 37.8645848, longitude: -122.2965778},
  {user_id: 22, gender: "male", orientation: nil, min_age: 15, max_age: 20, location: "Albany, CA", distance: 25, postal_code: "94706", latitude: 37.8883952, longitude: -122.2965778},
  {user_id: 23, gender: "female", orientation: "", min_age: 15, max_age: 20, location: "Richmond, CA", distance: 30, postal_code: "94804", latitude: 37.9158152, longitude: -122.3390936},
  {user_id: 24, gender: "female", orientation: nil, min_age: 15, max_age: 20, location: "El Sobrante, CA", distance: 25, postal_code: "94803", latitude: 37.9587253, longitude: -122.2767313},
  {user_id: 25, gender: "male", orientation: nil, min_age: 15, max_age: 20, location: "Richmond, CA", distance: 25, postal_code: "94805", latitude: 37.9383242, longitude: -122.3277578},
  {user_id: 26, gender: "female", orientation: nil, min_age: 14, max_age: 20, location: "San Pablo, CA", distance: 25, postal_code: "94806", latitude: 37.9759027, longitude: -122.3447611},
  {user_id: 27, gender: "female", orientation: nil, min_age: 14, max_age: 20, location: "El Cerrito, CA", distance: 25, postal_code: "94530", latitude: 37.9202057, longitude: -122.2937428},
  {user_id: 28, gender: nil, orientation: nil, min_age: 16, max_age: 22, location: "San Francisco, CA", distance: 25, postal_code: "94133", latitude: 37.8059887, longitude: -122.4099154},
  {user_id: 29, gender: "male", orientation: nil, min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94109", latitude: 37.7929789, longitude: -122.4212424},
  {user_id: 30, gender: "male", orientation: "", min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94109", latitude: 37.7929789, longitude: -122.4212424},
  {user_id: 31, gender: "male", orientation: nil, min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94109", latitude: 37.7929789, longitude: -122.4212424},
  {user_id: 32, gender: "male", orientation: nil, min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94109", latitude: 37.7929789, longitude: -122.4212424},
  {user_id: 33, gender: "male", orientation: "", min_age: 18, max_age: 24, location: "San Francisco, CA", distance: 25, postal_code: "94108", latitude: 37.7909427, longitude: -122.4084994},
  {user_id: 34, gender: "female", orientation: nil, min_age: 18, max_age: 25, location: "San Francisco, CA", distance: 25, postal_code: "94103", latitude: 37.7726402, longitude: -122.4099154},
  {user_id: 9, gender: "female", orientation: nil, min_age: 18, max_age: 25, location: "San Francisco, CA", distance: 25, postal_code: "94103", latitude: 37.7726402, longitude: -122.4099154},
  {user_id: 2, gender: "female", orientation: "", min_age: 16, max_age: 20, location: "San Diego, CA", distance: 25, postal_code: "92128", latitude: 33.0013938, longitude: -117.0735241}
])
Match.create!([
  {user_id: 2, match_id: 1},
  {user_id: 1, match_id: 2},
  {user_id: 3, match_id: 1},
  {user_id: 3, match_id: 2},
  {user_id: 1, match_id: 3},
  {user_id: 2, match_id: 3},
  {user_id: 4, match_id: 1},
  {user_id: 4, match_id: 3},
  {user_id: 4, match_id: 2},
  {user_id: 2, match_id: 4},
  {user_id: 5, match_id: 1},
  {user_id: 5, match_id: 3},
  {user_id: 5, match_id: 4},
  {user_id: 5, match_id: 2},
  {user_id: 6, match_id: 1},
  {user_id: 6, match_id: 3},
  {user_id: 6, match_id: 4},
  {user_id: 6, match_id: 2},
  {user_id: 6, match_id: 5},
  {user_id: 8, match_id: 1},
  {user_id: 8, match_id: 3},
  {user_id: 8, match_id: 4},
  {user_id: 8, match_id: 2},
  {user_id: 8, match_id: 7},
  {user_id: 8, match_id: 5},
  {user_id: 8, match_id: 6},
  {user_id: 2, match_id: 7},
  {user_id: 2, match_id: 5},
  {user_id: 2, match_id: 6},
  {user_id: 2, match_id: 8},
  {user_id: 10, match_id: 1},
  {user_id: 10, match_id: 2},
  {user_id: 10, match_id: 3},
  {user_id: 10, match_id: 4},
  {user_id: 10, match_id: 5},
  {user_id: 10, match_id: 6},
  {user_id: 10, match_id: 7},
  {user_id: 10, match_id: 8},
  {user_id: 11, match_id: 1},
  {user_id: 11, match_id: 2},
  {user_id: 11, match_id: 3},
  {user_id: 11, match_id: 4},
  {user_id: 11, match_id: 5},
  {user_id: 11, match_id: 6},
  {user_id: 11, match_id: 7},
  {user_id: 11, match_id: 8},
  {user_id: 11, match_id: 10},
  {user_id: 12, match_id: 1},
  {user_id: 12, match_id: 2},
  {user_id: 12, match_id: 3},
  {user_id: 12, match_id: 4},
  {user_id: 12, match_id: 5},
  {user_id: 12, match_id: 6},
  {user_id: 12, match_id: 7},
  {user_id: 12, match_id: 8},
  {user_id: 12, match_id: 10},
  {user_id: 12, match_id: 11},
  {user_id: 13, match_id: 1},
  {user_id: 13, match_id: 2},
  {user_id: 13, match_id: 3},
  {user_id: 13, match_id: 4},
  {user_id: 13, match_id: 5},
  {user_id: 13, match_id: 6},
  {user_id: 13, match_id: 7},
  {user_id: 13, match_id: 8},
  {user_id: 13, match_id: 10},
  {user_id: 13, match_id: 11},
  {user_id: 13, match_id: 12},
  {user_id: 14, match_id: 1},
  {user_id: 14, match_id: 2},
  {user_id: 14, match_id: 3},
  {user_id: 14, match_id: 4},
  {user_id: 14, match_id: 5},
  {user_id: 14, match_id: 6},
  {user_id: 14, match_id: 7},
  {user_id: 14, match_id: 8},
  {user_id: 14, match_id: 10},
  {user_id: 14, match_id: 11},
  {user_id: 14, match_id: 12},
  {user_id: 14, match_id: 13},
  {user_id: 15, match_id: 1},
  {user_id: 15, match_id: 2},
  {user_id: 15, match_id: 3},
  {user_id: 15, match_id: 4},
  {user_id: 15, match_id: 5},
  {user_id: 15, match_id: 6},
  {user_id: 15, match_id: 7},
  {user_id: 15, match_id: 8},
  {user_id: 15, match_id: 10},
  {user_id: 15, match_id: 11},
  {user_id: 15, match_id: 12},
  {user_id: 15, match_id: 13},
  {user_id: 15, match_id: 14},
  {user_id: 16, match_id: 1},
  {user_id: 16, match_id: 2},
  {user_id: 16, match_id: 3},
  {user_id: 16, match_id: 4},
  {user_id: 16, match_id: 5},
  {user_id: 16, match_id: 6},
  {user_id: 16, match_id: 7},
  {user_id: 16, match_id: 8},
  {user_id: 16, match_id: 10},
  {user_id: 16, match_id: 11},
  {user_id: 16, match_id: 15},
  {user_id: 16, match_id: 12},
  {user_id: 16, match_id: 13},
  {user_id: 16, match_id: 14},
  {user_id: 17, match_id: 1},
  {user_id: 17, match_id: 2},
  {user_id: 17, match_id: 3},
  {user_id: 17, match_id: 4},
  {user_id: 17, match_id: 5},
  {user_id: 17, match_id: 6},
  {user_id: 17, match_id: 7},
  {user_id: 17, match_id: 8},
  {user_id: 17, match_id: 10},
  {user_id: 17, match_id: 11},
  {user_id: 17, match_id: 15},
  {user_id: 17, match_id: 12},
  {user_id: 17, match_id: 13},
  {user_id: 17, match_id: 14},
  {user_id: 17, match_id: 16},
  {user_id: 18, match_id: 1},
  {user_id: 18, match_id: 2},
  {user_id: 18, match_id: 3},
  {user_id: 18, match_id: 4},
  {user_id: 18, match_id: 5},
  {user_id: 18, match_id: 6},
  {user_id: 18, match_id: 7},
  {user_id: 18, match_id: 8},
  {user_id: 18, match_id: 10},
  {user_id: 18, match_id: 11},
  {user_id: 18, match_id: 15},
  {user_id: 18, match_id: 12},
  {user_id: 18, match_id: 13},
  {user_id: 18, match_id: 14},
  {user_id: 18, match_id: 16},
  {user_id: 18, match_id: 17},
  {user_id: 19, match_id: 1},
  {user_id: 19, match_id: 2},
  {user_id: 19, match_id: 3},
  {user_id: 19, match_id: 4},
  {user_id: 19, match_id: 5},
  {user_id: 19, match_id: 6},
  {user_id: 19, match_id: 7},
  {user_id: 19, match_id: 8},
  {user_id: 19, match_id: 10},
  {user_id: 19, match_id: 11},
  {user_id: 19, match_id: 15},
  {user_id: 19, match_id: 12},
  {user_id: 19, match_id: 13},
  {user_id: 19, match_id: 14},
  {user_id: 19, match_id: 16},
  {user_id: 19, match_id: 17},
  {user_id: 19, match_id: 18},
  {user_id: 20, match_id: 1},
  {user_id: 20, match_id: 2},
  {user_id: 20, match_id: 3},
  {user_id: 20, match_id: 4},
  {user_id: 20, match_id: 5},
  {user_id: 20, match_id: 6},
  {user_id: 20, match_id: 7},
  {user_id: 20, match_id: 8},
  {user_id: 20, match_id: 10},
  {user_id: 20, match_id: 11},
  {user_id: 20, match_id: 15},
  {user_id: 20, match_id: 12},
  {user_id: 20, match_id: 13},
  {user_id: 20, match_id: 14},
  {user_id: 20, match_id: 16},
  {user_id: 20, match_id: 19},
  {user_id: 20, match_id: 17},
  {user_id: 20, match_id: 18},
  {user_id: 21, match_id: 1},
  {user_id: 21, match_id: 2},
  {user_id: 21, match_id: 3},
  {user_id: 21, match_id: 4},
  {user_id: 21, match_id: 5},
  {user_id: 21, match_id: 6},
  {user_id: 21, match_id: 7},
  {user_id: 21, match_id: 8},
  {user_id: 21, match_id: 10},
  {user_id: 21, match_id: 11},
  {user_id: 21, match_id: 15},
  {user_id: 21, match_id: 12},
  {user_id: 21, match_id: 13},
  {user_id: 21, match_id: 14},
  {user_id: 21, match_id: 16},
  {user_id: 21, match_id: 19},
  {user_id: 21, match_id: 17},
  {user_id: 21, match_id: 18},
  {user_id: 21, match_id: 20},
  {user_id: 22, match_id: 1},
  {user_id: 22, match_id: 2},
  {user_id: 22, match_id: 3},
  {user_id: 22, match_id: 4},
  {user_id: 22, match_id: 5},
  {user_id: 22, match_id: 6},
  {user_id: 22, match_id: 7},
  {user_id: 22, match_id: 8},
  {user_id: 22, match_id: 10},
  {user_id: 22, match_id: 11},
  {user_id: 22, match_id: 15},
  {user_id: 22, match_id: 12},
  {user_id: 22, match_id: 13},
  {user_id: 22, match_id: 14},
  {user_id: 22, match_id: 16},
  {user_id: 22, match_id: 19},
  {user_id: 22, match_id: 17},
  {user_id: 22, match_id: 18},
  {user_id: 22, match_id: 20},
  {user_id: 22, match_id: 21},
  {user_id: 23, match_id: 1},
  {user_id: 23, match_id: 2},
  {user_id: 23, match_id: 3},
  {user_id: 23, match_id: 4},
  {user_id: 23, match_id: 5},
  {user_id: 23, match_id: 6},
  {user_id: 23, match_id: 7},
  {user_id: 23, match_id: 8},
  {user_id: 23, match_id: 10},
  {user_id: 23, match_id: 11},
  {user_id: 23, match_id: 15},
  {user_id: 23, match_id: 12},
  {user_id: 23, match_id: 13},
  {user_id: 23, match_id: 14},
  {user_id: 23, match_id: 16},
  {user_id: 23, match_id: 19},
  {user_id: 23, match_id: 17},
  {user_id: 23, match_id: 18},
  {user_id: 23, match_id: 20},
  {user_id: 23, match_id: 21},
  {user_id: 23, match_id: 22},
  {user_id: 24, match_id: 1},
  {user_id: 24, match_id: 2},
  {user_id: 24, match_id: 3},
  {user_id: 24, match_id: 4},
  {user_id: 24, match_id: 5},
  {user_id: 24, match_id: 6},
  {user_id: 24, match_id: 7},
  {user_id: 24, match_id: 8},
  {user_id: 24, match_id: 10},
  {user_id: 24, match_id: 11},
  {user_id: 24, match_id: 15},
  {user_id: 24, match_id: 12},
  {user_id: 24, match_id: 13},
  {user_id: 24, match_id: 14},
  {user_id: 24, match_id: 16},
  {user_id: 24, match_id: 19},
  {user_id: 24, match_id: 17},
  {user_id: 24, match_id: 18},
  {user_id: 24, match_id: 20},
  {user_id: 24, match_id: 21},
  {user_id: 24, match_id: 22},
  {user_id: 24, match_id: 23},
  {user_id: 25, match_id: 1},
  {user_id: 25, match_id: 2},
  {user_id: 25, match_id: 3},
  {user_id: 25, match_id: 4},
  {user_id: 25, match_id: 5},
  {user_id: 25, match_id: 6},
  {user_id: 25, match_id: 7},
  {user_id: 25, match_id: 8},
  {user_id: 25, match_id: 10},
  {user_id: 25, match_id: 11},
  {user_id: 25, match_id: 15},
  {user_id: 25, match_id: 12},
  {user_id: 25, match_id: 13},
  {user_id: 25, match_id: 14},
  {user_id: 25, match_id: 16},
  {user_id: 25, match_id: 19},
  {user_id: 25, match_id: 17},
  {user_id: 25, match_id: 18},
  {user_id: 25, match_id: 20},
  {user_id: 25, match_id: 21},
  {user_id: 25, match_id: 22},
  {user_id: 25, match_id: 23},
  {user_id: 25, match_id: 24},
  {user_id: 26, match_id: 1},
  {user_id: 26, match_id: 2},
  {user_id: 26, match_id: 3},
  {user_id: 26, match_id: 4},
  {user_id: 26, match_id: 5},
  {user_id: 26, match_id: 6},
  {user_id: 26, match_id: 7},
  {user_id: 26, match_id: 8},
  {user_id: 26, match_id: 10},
  {user_id: 26, match_id: 11},
  {user_id: 26, match_id: 15},
  {user_id: 26, match_id: 12},
  {user_id: 26, match_id: 13},
  {user_id: 26, match_id: 14},
  {user_id: 26, match_id: 16},
  {user_id: 26, match_id: 19},
  {user_id: 26, match_id: 17},
  {user_id: 26, match_id: 18},
  {user_id: 26, match_id: 20},
  {user_id: 26, match_id: 21},
  {user_id: 26, match_id: 22},
  {user_id: 26, match_id: 23},
  {user_id: 26, match_id: 24},
  {user_id: 26, match_id: 25},
  {user_id: 27, match_id: 1},
  {user_id: 27, match_id: 2},
  {user_id: 27, match_id: 3},
  {user_id: 27, match_id: 4},
  {user_id: 27, match_id: 5},
  {user_id: 27, match_id: 6},
  {user_id: 27, match_id: 7},
  {user_id: 27, match_id: 8},
  {user_id: 27, match_id: 10},
  {user_id: 27, match_id: 11},
  {user_id: 27, match_id: 15},
  {user_id: 27, match_id: 12},
  {user_id: 27, match_id: 13},
  {user_id: 27, match_id: 14},
  {user_id: 27, match_id: 16},
  {user_id: 27, match_id: 19},
  {user_id: 27, match_id: 17},
  {user_id: 27, match_id: 18},
  {user_id: 27, match_id: 20},
  {user_id: 27, match_id: 21},
  {user_id: 27, match_id: 22},
  {user_id: 27, match_id: 23},
  {user_id: 27, match_id: 24},
  {user_id: 27, match_id: 25},
  {user_id: 27, match_id: 26},
  {user_id: 28, match_id: 1},
  {user_id: 28, match_id: 2},
  {user_id: 28, match_id: 3},
  {user_id: 28, match_id: 4},
  {user_id: 28, match_id: 5},
  {user_id: 28, match_id: 6},
  {user_id: 28, match_id: 7},
  {user_id: 28, match_id: 8},
  {user_id: 28, match_id: 10},
  {user_id: 28, match_id: 11},
  {user_id: 28, match_id: 15},
  {user_id: 28, match_id: 12},
  {user_id: 28, match_id: 13},
  {user_id: 28, match_id: 14},
  {user_id: 28, match_id: 16},
  {user_id: 28, match_id: 19},
  {user_id: 28, match_id: 17},
  {user_id: 28, match_id: 18},
  {user_id: 28, match_id: 20},
  {user_id: 28, match_id: 21},
  {user_id: 28, match_id: 22},
  {user_id: 28, match_id: 23},
  {user_id: 28, match_id: 24},
  {user_id: 28, match_id: 25},
  {user_id: 28, match_id: 26},
  {user_id: 28, match_id: 27},
  {user_id: 29, match_id: 1},
  {user_id: 29, match_id: 2},
  {user_id: 29, match_id: 3},
  {user_id: 29, match_id: 4},
  {user_id: 29, match_id: 5},
  {user_id: 29, match_id: 6},
  {user_id: 29, match_id: 7},
  {user_id: 29, match_id: 8},
  {user_id: 29, match_id: 10},
  {user_id: 29, match_id: 11},
  {user_id: 29, match_id: 15},
  {user_id: 29, match_id: 12},
  {user_id: 29, match_id: 13},
  {user_id: 29, match_id: 14},
  {user_id: 29, match_id: 16},
  {user_id: 29, match_id: 19},
  {user_id: 29, match_id: 17},
  {user_id: 29, match_id: 18},
  {user_id: 29, match_id: 20},
  {user_id: 29, match_id: 21},
  {user_id: 29, match_id: 22},
  {user_id: 29, match_id: 23},
  {user_id: 29, match_id: 24},
  {user_id: 29, match_id: 25},
  {user_id: 29, match_id: 26},
  {user_id: 29, match_id: 27},
  {user_id: 29, match_id: 28},
  {user_id: 30, match_id: 1},
  {user_id: 30, match_id: 2},
  {user_id: 30, match_id: 3},
  {user_id: 30, match_id: 4},
  {user_id: 30, match_id: 5},
  {user_id: 30, match_id: 6},
  {user_id: 30, match_id: 7},
  {user_id: 30, match_id: 8},
  {user_id: 30, match_id: 10},
  {user_id: 30, match_id: 11},
  {user_id: 30, match_id: 15},
  {user_id: 30, match_id: 12},
  {user_id: 30, match_id: 13},
  {user_id: 30, match_id: 14},
  {user_id: 30, match_id: 16},
  {user_id: 30, match_id: 19},
  {user_id: 30, match_id: 17},
  {user_id: 30, match_id: 18},
  {user_id: 30, match_id: 20},
  {user_id: 30, match_id: 21},
  {user_id: 30, match_id: 22},
  {user_id: 30, match_id: 23},
  {user_id: 30, match_id: 24},
  {user_id: 30, match_id: 25},
  {user_id: 30, match_id: 26},
  {user_id: 30, match_id: 27},
  {user_id: 30, match_id: 28},
  {user_id: 30, match_id: 29},
  {user_id: 31, match_id: 1},
  {user_id: 31, match_id: 2},
  {user_id: 31, match_id: 3},
  {user_id: 31, match_id: 4},
  {user_id: 31, match_id: 5},
  {user_id: 31, match_id: 6},
  {user_id: 31, match_id: 7},
  {user_id: 31, match_id: 8},
  {user_id: 31, match_id: 10},
  {user_id: 31, match_id: 11},
  {user_id: 31, match_id: 15},
  {user_id: 31, match_id: 12},
  {user_id: 31, match_id: 13},
  {user_id: 31, match_id: 14},
  {user_id: 31, match_id: 16},
  {user_id: 31, match_id: 19},
  {user_id: 31, match_id: 17},
  {user_id: 31, match_id: 18},
  {user_id: 31, match_id: 20},
  {user_id: 31, match_id: 21},
  {user_id: 31, match_id: 22},
  {user_id: 31, match_id: 23},
  {user_id: 31, match_id: 24},
  {user_id: 31, match_id: 25},
  {user_id: 31, match_id: 26},
  {user_id: 31, match_id: 27},
  {user_id: 31, match_id: 28},
  {user_id: 31, match_id: 29},
  {user_id: 31, match_id: 30},
  {user_id: 32, match_id: 1},
  {user_id: 32, match_id: 2},
  {user_id: 32, match_id: 3},
  {user_id: 32, match_id: 4},
  {user_id: 32, match_id: 5},
  {user_id: 32, match_id: 6},
  {user_id: 32, match_id: 7},
  {user_id: 32, match_id: 8},
  {user_id: 32, match_id: 10},
  {user_id: 32, match_id: 11},
  {user_id: 32, match_id: 15},
  {user_id: 32, match_id: 12},
  {user_id: 32, match_id: 13},
  {user_id: 32, match_id: 14},
  {user_id: 32, match_id: 16},
  {user_id: 32, match_id: 19},
  {user_id: 32, match_id: 17},
  {user_id: 32, match_id: 18},
  {user_id: 32, match_id: 20},
  {user_id: 32, match_id: 21},
  {user_id: 32, match_id: 22},
  {user_id: 32, match_id: 23},
  {user_id: 32, match_id: 24},
  {user_id: 32, match_id: 25},
  {user_id: 32, match_id: 26},
  {user_id: 32, match_id: 27},
  {user_id: 32, match_id: 28},
  {user_id: 32, match_id: 29},
  {user_id: 32, match_id: 30},
  {user_id: 32, match_id: 31},
  {user_id: 33, match_id: 1},
  {user_id: 33, match_id: 2},
  {user_id: 33, match_id: 3},
  {user_id: 33, match_id: 4},
  {user_id: 33, match_id: 5},
  {user_id: 33, match_id: 6},
  {user_id: 33, match_id: 7},
  {user_id: 33, match_id: 8},
  {user_id: 33, match_id: 10},
  {user_id: 33, match_id: 11},
  {user_id: 33, match_id: 15},
  {user_id: 33, match_id: 12},
  {user_id: 33, match_id: 13},
  {user_id: 33, match_id: 14},
  {user_id: 33, match_id: 16},
  {user_id: 33, match_id: 19},
  {user_id: 33, match_id: 17},
  {user_id: 33, match_id: 18},
  {user_id: 33, match_id: 20},
  {user_id: 33, match_id: 21},
  {user_id: 33, match_id: 22},
  {user_id: 33, match_id: 23},
  {user_id: 33, match_id: 24},
  {user_id: 33, match_id: 25},
  {user_id: 33, match_id: 26},
  {user_id: 33, match_id: 27},
  {user_id: 33, match_id: 28},
  {user_id: 33, match_id: 29},
  {user_id: 33, match_id: 30},
  {user_id: 33, match_id: 31},
  {user_id: 33, match_id: 32},
  {user_id: 34, match_id: 1},
  {user_id: 34, match_id: 2},
  {user_id: 34, match_id: 3},
  {user_id: 34, match_id: 4},
  {user_id: 34, match_id: 5},
  {user_id: 34, match_id: 6},
  {user_id: 34, match_id: 7},
  {user_id: 34, match_id: 8},
  {user_id: 34, match_id: 10},
  {user_id: 34, match_id: 11},
  {user_id: 34, match_id: 15},
  {user_id: 34, match_id: 12},
  {user_id: 34, match_id: 13},
  {user_id: 34, match_id: 14},
  {user_id: 34, match_id: 16},
  {user_id: 34, match_id: 19},
  {user_id: 34, match_id: 17},
  {user_id: 34, match_id: 18},
  {user_id: 34, match_id: 20},
  {user_id: 34, match_id: 21},
  {user_id: 34, match_id: 22},
  {user_id: 34, match_id: 23},
  {user_id: 34, match_id: 24},
  {user_id: 34, match_id: 25},
  {user_id: 34, match_id: 26},
  {user_id: 34, match_id: 27},
  {user_id: 34, match_id: 28},
  {user_id: 34, match_id: 29},
  {user_id: 34, match_id: 30},
  {user_id: 34, match_id: 31},
  {user_id: 34, match_id: 32},
  {user_id: 34, match_id: 33},
  {user_id: 2, match_id: 10},
  {user_id: 2, match_id: 11},
  {user_id: 2, match_id: 15},
  {user_id: 2, match_id: 12},
  {user_id: 2, match_id: 13},
  {user_id: 2, match_id: 14},
  {user_id: 2, match_id: 16},
  {user_id: 2, match_id: 19},
  {user_id: 2, match_id: 17},
  {user_id: 2, match_id: 18},
  {user_id: 2, match_id: 20},
  {user_id: 2, match_id: 21},
  {user_id: 2, match_id: 22},
  {user_id: 2, match_id: 23},
  {user_id: 2, match_id: 24},
  {user_id: 2, match_id: 25},
  {user_id: 2, match_id: 26},
  {user_id: 2, match_id: 27},
  {user_id: 2, match_id: 28},
  {user_id: 2, match_id: 29},
  {user_id: 2, match_id: 30},
  {user_id: 2, match_id: 31},
  {user_id: 2, match_id: 32},
  {user_id: 2, match_id: 33},
  {user_id: 2, match_id: 34},
  {user_id: 2, match_id: 9},
  {user_id: 1, match_id: 4},
  {user_id: 1, match_id: 5},
  {user_id: 1, match_id: 6},
  {user_id: 1, match_id: 7},
  {user_id: 1, match_id: 8},
  {user_id: 1, match_id: 9},
  {user_id: 1, match_id: 10},
  {user_id: 1, match_id: 11},
  {user_id: 1, match_id: 12},
  {user_id: 1, match_id: 13},
  {user_id: 1, match_id: 14},
  {user_id: 1, match_id: 15},
  {user_id: 1, match_id: 16},
  {user_id: 1, match_id: 17},
  {user_id: 1, match_id: 18},
  {user_id: 1, match_id: 19},
  {user_id: 1, match_id: 20},
  {user_id: 1, match_id: 21},
  {user_id: 1, match_id: 22},
  {user_id: 1, match_id: 23},
  {user_id: 1, match_id: 24},
  {user_id: 1, match_id: 25},
  {user_id: 1, match_id: 26},
  {user_id: 1, match_id: 27},
  {user_id: 1, match_id: 28},
  {user_id: 1, match_id: 29},
  {user_id: 1, match_id: 30},
  {user_id: 1, match_id: 31},
  {user_id: 1, match_id: 32},
  {user_id: 1, match_id: 33},
  {user_id: 1, match_id: 34},
  {user_id: 20, match_id: 9},
  {user_id: 20, match_id: 21},
  {user_id: 20, match_id: 22},
  {user_id: 20, match_id: 23},
  {user_id: 20, match_id: 24},
  {user_id: 20, match_id: 25},
  {user_id: 20, match_id: 26},
  {user_id: 20, match_id: 27},
  {user_id: 20, match_id: 28},
  {user_id: 20, match_id: 29},
  {user_id: 20, match_id: 30},
  {user_id: 20, match_id: 31},
  {user_id: 20, match_id: 32},
  {user_id: 20, match_id: 33},
  {user_id: 20, match_id: 34}
])
Message.create!([
  {author_id: 2, thread_id: 1, body: "HI there! Have we met? You seem a little familiar...\n\nThe name's Josuke, by the way.", read: false},
  {author_id: 20, thread_id: 1, body: "No way! I know a guy named Josuke who looks almost exactly like you! FREAKY", read: false}
])
MessageThread.create!([
  {sender_id: 2, recipient_id: 20}
])
Question.create!([
  {body: "What do the planets of the solar system revolve around?"},
  {body: "Are you a morning person?"},
  {body: "Could you date someone who was really messy?"},
  {body: "Do you ever ignore people?"},
  {body: "Are you a cat person or a dog person?"},
  {body: "Are you either vegetarian or vegan?"},
  {body: "If you had to name your greatest motivation in life thus far, what would it be?"},
  {body: "If you don't do anything at all for an entire day, how does that make you feel?"},
  {body: "Do you like to cuddle?"},
  {body: "Can anything be made the subject of a joke?"},
  {body: "Do you believe in fate?"},
  {body: "Is jealousy healthy in a relationship?"},
  {body: "Do you enjoy intense intellectual conversations?"},
  {body: "Do you often find yourself worrying about things that you have no control over?"},
  {body: "Is love overrated?"},
  {body: "Outside of work and school, how inclined are you to investigate something that interests you?"},
  {body: "When men show extra courtesy toward women (opening doors, pulling out chairs, etc.), this is:"}
])
User.create!([
  {username: "rakuraku15", password_digest: "$2a$10$Om1ZTZTjfbi/3DTMNo/B3.g8ion69G/RNu5vOCaMrNs9vALecXTqa", session_token: "CCPQcAbnuAmVZeZpNdlYLg", avatar_url: "GenkiCupid_Avatars/d3vtyklamxulew3xxplh.jpg", postal_code: "94536", birthdate: "1998-05-15 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "DiamondJoe", password_digest: "$2a$10$DDdryKDm4UY/K0phU8w9felP/K0Dnn0c3oJ3xPsDTSEN3.CVHq4my", session_token: "ZkW1X9pmjTw3rE1r_YmNYw", avatar_url: "GenkiCupid_Avatars/josuke_higashikata.png", postal_code: "94703", birthdate: "2000-04-04 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.8524741, longitude: -122.2738958, location: "Berkeley, CA"},
  {username: "GoriGurrl", password_digest: "$2a$10$jNaMRcB4//jU50bH88C8WOz6kfTllMkhtXgUvoEY7jIwCgAkYH5pO", session_token: "y1evDUcmW4A4NffDJpYYVA", avatar_url: "GenkiCupid_Avatars/pmpct75kf79wzr0wlk6f.png", postal_code: "94536", birthdate: "1998-07-07 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "rurin", password_digest: "$2a$10$MwfLswK4bWI6HNoCza5Ltumf/NpQpoOk7gfirWA2Dadiod6xpG5ci", session_token: "HZm5gEwj57w0UsyrSu5NzQ", avatar_url: "GenkiCupid_Avatars/mujjvlubzqqmbro3wfp7.jpg", postal_code: "94539", birthdate: "1998-03-29 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.5148444, longitude: -121.9131761, location: "Fremont, CA"},
  {username: "tsugumin", password_digest: "$2a$10$7ary2J2AkXOrCxOUQMpIY.gnNf6kudhCIvegOnVUbCEmsYwNspaES", session_token: "ImgnPlet8BX-MpTrKYiALA", avatar_url: "GenkiCupid_Avatars/vnyevur5lzwseeopv5i6.png", postal_code: "94536", birthdate: "1998-08-08 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "Deradere", password_digest: "$2a$10$ocgwXyCNFznJvRxObT.rkOGXKVfRZ2FiZZwD0XAanLd9F6CtDO5xG", session_token: "niRNHzRJemMHqVZz6aH3Xw", avatar_url: "GenkiCupid_Avatars/gmemqp65ny8ps74vcncq.jpg", postal_code: "94536", birthdate: "1998-07-07 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "HotMike", password_digest: "$2a$10$LuLJOp6WKxIEEREquXOwEu.XdeHuCm8SNJxnwl.tUSX8FaMQ2esHq", session_token: "zyTWdA-8W1SBODFfQX2jFg", avatar_url: "GenkiCupid_Avatars/lc3l7a8hmazrducvowk0.jpg", postal_code: "94536", birthdate: "1998-01-18 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "harudera", password_digest: "$2a$10$Fjbpqo5hY2nF1ov/nV19oO3RvAVeAKCVT2EauAoMpJsIjNdnnV3Gu", session_token: "nh_TBWKqTryoenoG-Baa4w", avatar_url: "GenkiCupid_Avatars/l98qpw3deqhxllyo07be.jpg", postal_code: "94536", birthdate: "1999-09-04 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.5641425, longitude: -122.004179, location: "Fremont, CA"},
  {username: "lodsofemone", password_digest: "$2a$10$At8rQEgN1x9k5oYY8AZwaeOe50FPXhJ4SMoulJLWJY1h6qYKw.Vkq", session_token: "j_GLfxnxUV7WVpDJa0kHUg", avatar_url: "GenkiCupid_Avatars/xl7kaub0ifneuefasfah.jpg", postal_code: "94103", birthdate: "1995-08-08 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.7726402, longitude: -122.4099154, location: "San Francisco, CA"},
  {username: "IsRyudo", password_digest: "$2a$10$Pybvohp8wRb7BvQujBOrC.PqKuM1VBqE6XY9KP.ulJjH29fAeapFa", session_token: "mSDwUiL9WBy7_wBKMzZXNg", avatar_url: "GenkiCupid_Avatars/khyatod0s6fg2uqfj7xi.jpg", postal_code: "94121", birthdate: "1998-03-24 00:00:00", gender: "male", orientation: "gay", rel_status: "single", latitude: 37.7813454, longitude: -122.497668, location: "San Francisco, CA"},
  {username: "cherryai", password_digest: "$2a$10$6XtygFUehMU878Vy6Ayu8uo/ftyZ7LZsMSo9Td.Hs/hYJI4OBsXaq", session_token: "OHFbN95RWolK9orpzX_OWA", avatar_url: "GenkiCupid_Avatars/zkvisav4yofrxdpukgnj.jpg", postal_code: "94118", birthdate: "2000-05-05 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7822891, longitude: -122.463708, location: "San Francisco, CA"},
  {username: "yumifreak", password_digest: "$2a$10$m/MFcdu8Ig72NkX3UI9nA.EGkuulT5OVCIKZMnstzYhVgXuz7R/vG", session_token: "y6LmiCvEg3aJ_AwMGSHcmg", avatar_url: "GenkiCupid_Avatars/mwpdku0stw8dunebbbyv.jpg", postal_code: "94122", birthdate: "1998-06-05 00:00:00", gender: "female", orientation: "gay", rel_status: "single", latitude: 37.7597481, longitude: -122.4750292, location: "San Francisco, CA"},
  {username: "KaleidoRuby", password_digest: "$2a$10$1Ndz3pRNibOgp23X16i9.OslgQ4pPptX1M5e2Yjpwb09JCF24BW5K", session_token: "_hp_2qOkFygWKAoxbdCC_Q", avatar_url: "GenkiCupid_Avatars/cbrff7y4cnfjvxllegj7.png", postal_code: "94116", birthdate: "1999-02-03 00:00:00", gender: "female", orientation: "bisexual", rel_status: "single", latitude: 37.7432421, longitude: -122.497668, location: "San Francisco, CA"},
  {username: "arturia", password_digest: "$2a$10$FjgVSTa3RQqj0lhajUFXIe/l4bJkfWb.zR3V4F4fVy1MSu25EZIJm", session_token: "uUf0opLZ-wZLweosgG7ifA", avatar_url: "GenkiCupid_Avatars/ydisj8ljljl3pwfqamuc.jpg", postal_code: "94131", birthdate: "1997-09-09 00:00:00", gender: "female", orientation: "bisexual", rel_status: "single", latitude: 37.7401042, longitude: -122.4382307, location: "San Francisco, CA"},
  {username: "seaweed", password_digest: "$2a$10$BwW2Q8cVUCdoRHs1osHZGuj//0ssy/dl6W12I1og6zDZpDXflihpC", session_token: "MHNl11mZbWS4s1MynNqcKA", avatar_url: "GenkiCupid_Avatars/ffmerrulwbchn9gusf1j.jpg", postal_code: "94118", birthdate: "1999-07-19 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.7822891, longitude: -122.463708, location: "San Francisco, CA"},
  {username: "NoDignity", password_digest: "$2a$10$LCYw.lfXtAFJlLpZiLzFL.46mwBIlq7oxvmfLih4PurmIQ46Iv8ZW", session_token: "ZnJt-Ym3tCXFdqSzDLUt_Q", avatar_url: "GenkiCupid_Avatars/kvhk6oac8m8xix5wtxnr.png", postal_code: "94710", birthdate: "2000-05-01 00:00:00", gender: "male", orientation: "straight", rel_status: "dating", latitude: 37.8645848, longitude: -122.2965778, location: "Berkeley, CA"},
  {username: "EmiyaShirou", password_digest: "$2a$10$ZfwVq.cRnrMjuCuQBFrvYu807WQjUwXfBohL1KsfU2hOM/wWh4BzK", session_token: "OOhDvpK2y6GtPF1nZinSUA", avatar_url: "GenkiCupid_Avatars/bk0mfedss0w90zddylgc.jpg", postal_code: "94121", birthdate: "1998-12-07 00:00:00", gender: "male", orientation: "bisexual", rel_status: "single", latitude: 37.7813454, longitude: -122.497668, location: "San Francisco, CA"},
  {username: "ElMelloiII", password_digest: "$2a$10$6YGLP8xQIvwO4B4eO3EBM.Pthybp/lXYiPCB8Im80ySacN5/VilFO", session_token: "eJ43ooYwS7EVY-WIHRxu-g", avatar_url: "GenkiCupid_Avatars/y8ueyh40p4gu3tnyqwvd.jpg", postal_code: "94114", birthdate: "2000-04-16 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.7561438, longitude: -122.4325682, location: "San Francisco, CA"},
  {username: "billionbucks", password_digest: "$2a$10$L0lB912Yn.muirPV/gOUlu9IfJe4BEQm2TozK.ITsJ1ahpfTXVPJS", session_token: "6_wGidNTtUQowotUJw56XA", avatar_url: "GenkiCupid_Avatars/kjmcbmsfmurtzmchwpf4.jpg", postal_code: "94702", birthdate: "1999-10-09 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.8680576, longitude: -122.2852374, location: "Berkeley, CA"},
  {username: "PaisleyPark", password_digest: "$2a$10$zhCgMMaanli3eMi5qQwtXuUXnHshRwkFJfCLNcb0jnU6kmIDsVoui", session_token: "Jwaeg19e-AOKrbZlyMBjNQ", avatar_url: "GenkiCupid_Avatars/wenv4rv2wwagur7oidd6.jpg", postal_code: "94710", birthdate: "1999-06-06 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.8645848, longitude: -122.2965778, location: "Berkeley, CA"},
  {username: "LoveDeluxe", password_digest: "$2a$10$f3q02t4Um.cRAYmYksUzQuc4GOa78.Ho3kgQ1EoEfNj7lgJ.ARZpe", session_token: "_tgHwMhMjVZ-2gE8eW4zdQ", avatar_url: "GenkiCupid_Avatars/eqnfhqdhgh7tjqdjtkgu.jpg", postal_code: "94706", birthdate: "1999-06-23 00:00:00", gender: "female", orientation: "straight", rel_status: "dating", latitude: 37.8883952, longitude: -122.2965778, location: "Albany, CA"},
  {username: "hinata251", password_digest: "$2a$10$1M9QlPnZ1ZdtfpR6OQkY/eGo8kIqc3raDc8oxCfFMrhPZwkJ5Q2We", session_token: "WjtMwIYyBXZ--TRHeOTc0A", avatar_url: "GenkiCupid_Avatars/kvtb3wghk8zvijuwxivs.jpg", postal_code: "94804", birthdate: "1999-07-22 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.9158152, longitude: -122.3390936, location: "Richmond, CA"},
  {username: "TigerEye", password_digest: "$2a$10$krLQiKuIzVUD021L5yQ0jOxcdfNOSFdf/scwYrgQpOETDvTp6dWRi", session_token: "8l3JB0riZPQ0iBZDqsyQlw", avatar_url: "GenkiCupid_Avatars/igaaajwthwvmzidzmugb.png", postal_code: "94803", birthdate: "1999-06-08 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.9587253, longitude: -122.2767313, location: "El Sobrante, CA"},
  {username: "BeeMaiden", password_digest: "$2a$10$zj660hOTMG8LoPQtQJCJq.MpYO3UAey9uEE96jz5rBTmJNg6/JwUy", session_token: "wYDQsMhAgIeQrNR7m2AX1A", avatar_url: "GenkiCupid_Avatars/wlycxsdx3cqssftd8iob.png", postal_code: "94805", birthdate: "1999-04-15 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.9383242, longitude: -122.3277578, location: "Richmond, CA"},
  {username: "Hypemaster", password_digest: "$2a$10$Y22Wh4VAmkepRCPP2YyGKejoGfnXc1YYh7jMR8NJ2IeyyeuaTk.O2", session_token: "GK1hIzvjKxgrySRkdOi_YQ", avatar_url: "GenkiCupid_Avatars/wwc9ejsd2ficb8prk6ip.png", postal_code: "94806", birthdate: "2000-03-03 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.9759027, longitude: -122.3447611, location: "San Pablo, CA"},
  {username: "bunnysamurai", password_digest: "$2a$10$YHaAOLX8f7jO8X5rvmmcSeZfU7q/V1P4vyKG/8sRKqF6WQukSWxq2", session_token: "VT6Kc0wLHIY50Nt-6h_b3Q", avatar_url: "GenkiCupid_Avatars/csup2lqu8pe87e7ggspv.jpg", postal_code: "94530", birthdate: "2000-05-22 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.9202057, longitude: -122.2937428, location: "El Cerrito, CA"},
  {username: "chocobanana", password_digest: "$2a$10$haPje2Ej23s4kIO1NgULceyu9V3/l9WD5FBjJx82lJ4mxlHLOwHTS", session_token: "yE9B1YCOKDL_iX9P83jQNw", avatar_url: "GenkiCupid_Avatars/p3nvvoeeqlu3sxiglkoy.jpg", postal_code: "94133", birthdate: "1998-01-28 00:00:00", gender: "female", orientation: "bisexual", rel_status: "single", latitude: 37.8059887, longitude: -122.4099154, location: "San Francisco, CA"},
  {username: "Myamura", password_digest: "$2a$10$sJE5YBH7/ky9/MjVVofZHOoY3N.UCUxgkTbeLmKDBHfWxNPQrc6O2", session_token: "6qh87DOORZ5om92c3QI7fg", avatar_url: "GenkiCupid_Avatars/oloxcheckamnlnojzkop.jpg", postal_code: "94109", birthdate: "1996-06-25 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7929789, longitude: -122.4212424, location: "San Francisco, CA"},
  {username: "EmaDraws", password_digest: "$2a$10$pvs1Vh1nyOWJEQHDaQG/1eqSWt4NlsUZPDR3rtp974VD/J1d/YZ2W", session_token: "7bFyuMzNts0uWuSzcPt_aw", avatar_url: "GenkiCupid_Avatars/prcgvh2aqspdqigwfaqa.jpg", postal_code: "94109", birthdate: "1996-02-25 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7929789, longitude: -122.4212424, location: "San Francisco, CA"},
  {username: "hounddog", password_digest: "$2a$10$QJZ1Zibi7GBM.wUvHdRO0uLNnbaMAby.n1JOiC06qBiTY9uF6UDru", session_token: "7ebYMxn5RZY3DjdbKR6x3w", avatar_url: "GenkiCupid_Avatars/oweb1ncpurym6yr25kmj.png", postal_code: "94132", birthdate: "1995-04-12 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.7181398, longitude: -122.4863492, location: "San Francisco, CA"},
  {username: "Miichan", password_digest: "$2a$10$4WgwuxNvwFvOfrZLZBg9J.aSO5LWePv.G8p5C15ewLTVpOBNdRDyG", session_token: "SPhkRKrTZWaPPX836ARLfg", avatar_url: "GenkiCupid_Avatars/qezaftdjzk8vcmppoggx.jpg", postal_code: "94109", birthdate: "1996-03-17 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7929789, longitude: -122.4212424, location: "San Francisco, CA"},
  {username: "Misa3D", password_digest: "$2a$10$8Chs2O1itl/lQFPTSpfT9u/KY4dN9R.1cIMrxz8szKms8RrcNRYcm", session_token: "kq1E5OyDu9mYdNecxiP2iw", avatar_url: "GenkiCupid_Avatars/tcwknlzz0n0pdffw2sdf.jpg", postal_code: "94109", birthdate: "1996-07-14 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7929789, longitude: -122.4212424, location: "San Francisco, CA"},
  {username: "QuietSparkle", password_digest: "$2a$10$C4GE18HVuqauVQbso7xssO05URv1sqo3lwx8X2iIDiIc27G1L8Zdm", session_token: "Qkb5cxeZypTYm02s-3jYGg", avatar_url: "GenkiCupid_Avatars/w8b79u1d8xb4j9xci8ts.jpg", postal_code: "94108", birthdate: "1995-09-01 00:00:00", gender: "female", orientation: "straight", rel_status: "single", latitude: 37.7909427, longitude: -122.4084994, location: "San Francisco, CA"},
  {username: "CoolTarou", password_digest: "$2a$10$l6aPKnLSVRrllPgMvhsfNuRz7lifEqvNy2HWhP40fCy9FCTygTnbO", session_token: "MgP3PiI1T64MEkn6pdfpAA", avatar_url: "GenkiCupid_Avatars/hcxld4uenmopigo67gtj.jpg", postal_code: "94103", birthdate: "1995-02-06 00:00:00", gender: "male", orientation: "straight", rel_status: "single", latitude: 37.7726402, longitude: -122.4099154, location: "San Francisco, CA"}
])
